#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

/* Definition for CPU ID */
#define XPAR_CPU_ID 0U

/* Definitions for peripheral PSV_CORTEXA72_0 */
#define XPAR_PSV_CORTEXA72_0_CPU_CLK_FREQ_HZ 999989990
#define XPAR_PSV_CORTEXA72_0_TIMESTAMP_CLK_FREQ 99999001


/******************************************************************/

/* Canonical definitions for peripheral PSV_CORTEXA72_0 */
#define XPAR_CPU_CORTEXA72_0_CPU_CLK_FREQ_HZ 999989990
#define XPAR_CPU_CORTEXA72_0_TIMESTAMP_CLK_FREQ 99999001


/******************************************************************/

 /* Definition for PSS REF CLK FREQUENCY */
#define XPAR_PSU_PSS_REF_CLK_FREQ_HZ 33333000U

#include "xparameters_ps.h"


/* Number of Fabric Resets */

#define STDIN_BASEADDRESS 0xFF000000
#define STDOUT_BASEADDRESS 0xFF000000

/******************************************************************/

/* Platform specific definitions */
#ifndef versal
#define versal
#endif

 
/* Definitions for sleep timer configuration */
#define XSLEEP_TIMER_IS_DEFAULT_TIMER
 
 
/******************************************************************/
/* Definitions for driver CANFD */
#define XPAR_XCANFD_NUM_INSTANCES 2

/* Definitions for peripheral PSV_CANFD_0 */
#define XPAR_PSV_CANFD_0_DEVICE_ID 0
#define XPAR_PSV_CANFD_0_BASEADDR 0xFF060000
#define XPAR_PSV_CANFD_0_HIGHADDR 0xFF06FFFF
#define XPAR_PSV_CANFD_0_CAN_RX_DPTH 64
#define XPAR_PSV_CANFD_0_CAN_TX_DPTH 32
#define XPAR_PSV_CANFD_0_RX_MODE 0
#define XPAR_PSV_CANFD_0_NUM_OF_RX_MB_BUF 48
#define XPAR_PSV_CANFD_0_NUM_OF_TX_BUF 32
#define XPAR_PSV_CANFD_0_CAN_CLK_FREQ_HZ 149998505


/* Definitions for peripheral PSV_CANFD_1 */
#define XPAR_PSV_CANFD_1_DEVICE_ID 1
#define XPAR_PSV_CANFD_1_BASEADDR 0xFF070000
#define XPAR_PSV_CANFD_1_HIGHADDR 0xFF07FFFF
#define XPAR_PSV_CANFD_1_CAN_RX_DPTH 64
#define XPAR_PSV_CANFD_1_CAN_TX_DPTH 32
#define XPAR_PSV_CANFD_1_RX_MODE 0
#define XPAR_PSV_CANFD_1_NUM_OF_RX_MB_BUF 48
#define XPAR_PSV_CANFD_1_NUM_OF_TX_BUF 32
#define XPAR_PSV_CANFD_1_CAN_CLK_FREQ_HZ 149998505


/******************************************************************/

/* Canonical definitions for peripheral PSV_CANFD_0 */
#define XPAR_CANFD_0_DEVICE_ID XPAR_PSV_CANFD_0_DEVICE_ID
#define XPAR_CANFD_0_BASEADDR 0xFF060000
#define XPAR_CANFD_0_HIGHADDR 0xFF06FFFF
#define XPAR_CANFD_0_CAN_RX_DPTH 64
#define XPAR_CANFD_0_CAN_TX_DPTH 32
#define XPAR_CANFD_0_RX_MODE 0
#define XPAR_CANFD_0_NUM_OF_RX_MB_BUF 48
#define XPAR_CANFD_0_NUM_OF_TX_BUF 32
#define XPAR_CANFD_0_CAN_CLK_FREQ_HZ 149998505

/* Canonical definitions for peripheral PSV_CANFD_1 */
#define XPAR_CANFD_1_DEVICE_ID XPAR_PSV_CANFD_1_DEVICE_ID
#define XPAR_CANFD_1_BASEADDR 0xFF070000
#define XPAR_CANFD_1_HIGHADDR 0xFF07FFFF
#define XPAR_CANFD_1_CAN_RX_DPTH 64
#define XPAR_CANFD_1_CAN_TX_DPTH 32
#define XPAR_CANFD_1_RX_MODE 0
#define XPAR_CANFD_1_NUM_OF_RX_MB_BUF 48
#define XPAR_CANFD_1_NUM_OF_TX_BUF 32
#define XPAR_CANFD_1_CAN_CLK_FREQ_HZ 149998505


/******************************************************************/

#define XPAR_CANFD_ISPS
/* Definitions for driver CFRAME */
#define XPAR_XCFRAME_NUM_INSTANCES 1

/* Definitions for peripheral PSV_PMC_CFI_CFRAME_0 */
#define XPAR_PSV_PMC_CFI_CFRAME_0_DEVICE_ID 0
#define XPAR_PSV_PMC_CFI_CFRAME_0_BASEADDR 0xF12D0000
#define XPAR_PSV_PMC_CFI_CFRAME_0_HIGHADDR 0xF12D0FFF


/******************************************************************/

/* Canonical definitions for peripheral PSV_PMC_CFI_CFRAME_0 */
#define XPAR_XCFRAME_0_DEVICE_ID XPAR_PSV_PMC_CFI_CFRAME_0_DEVICE_ID
#define XPAR_XCFRAME_0_BASEADDR 0xF12D0000
#define XPAR_XCFRAME_0_HIGHADDR 0xF12D0FFF


/******************************************************************/

/* Definitions for driver CFUPMC */
#define XPAR_XCFUPMC_NUM_INSTANCES 1

/* Definitions for peripheral PSV_PMC_CFU_APB_0 */
#define XPAR_PSV_PMC_CFU_APB_0_DEVICE_ID 0
#define XPAR_PSV_PMC_CFU_APB_0_BASEADDR 0xF12B0000
#define XPAR_PSV_PMC_CFU_APB_0_HIGHADDR 0xF12BFFFF


/******************************************************************/

/* Canonical definitions for peripheral PSV_PMC_CFU_APB_0 */
#define XPAR_XCFUPMC_0_DEVICE_ID XPAR_PSV_PMC_CFU_APB_0_DEVICE_ID
#define XPAR_XCFUPMC_0_BASEADDR 0xF12B0000
#define XPAR_XCFUPMC_0_HIGHADDR 0xF12BFFFF


/******************************************************************/

/* Definitions for driver CSUDMA */
#define XPAR_XCSUDMA_NUM_INSTANCES 2

/* Definitions for peripheral PSV_PMC_DMA_0 */
#define XPAR_PSV_PMC_DMA_0_DEVICE_ID 0
#define XPAR_PSV_PMC_DMA_0_BASEADDR 0xF11C0000
#define XPAR_PSV_PMC_DMA_0_HIGHADDR 0xF11CFFFF
#define XPAR_PSV_PMC_DMA_0_CSUDMA_CLK_FREQ_HZ 0


/* Definitions for peripheral PSV_PMC_DMA_1 */
#define XPAR_PSV_PMC_DMA_1_DEVICE_ID 1
#define XPAR_PSV_PMC_DMA_1_BASEADDR 0xF11D0000
#define XPAR_PSV_PMC_DMA_1_HIGHADDR 0xF11DFFFF
#define XPAR_PSV_PMC_DMA_1_CSUDMA_CLK_FREQ_HZ 0


/******************************************************************/

#define XPAR_PSV_PMC_DMA_0_DMATYPE 1
#define XPAR_PSV_PMC_DMA_1_DMATYPE 2
/* Canonical definitions for peripheral PSV_PMC_DMA_0 */
#define XPAR_XCSUDMA_0_DEVICE_ID XPAR_PSV_PMC_DMA_0_DEVICE_ID
#define XPAR_XCSUDMA_0_BASEADDR 0xF11C0000
#define XPAR_XCSUDMA_0_HIGHADDR 0xF11CFFFF
#define XPAR_XCSUDMA_0_CSUDMA_CLK_FREQ_HZ 0

/* Canonical definitions for peripheral PSV_PMC_DMA_1 */
#define XPAR_XCSUDMA_1_DEVICE_ID XPAR_PSV_PMC_DMA_1_DEVICE_ID
#define XPAR_XCSUDMA_1_BASEADDR 0xF11D0000
#define XPAR_XCSUDMA_1_HIGHADDR 0xF11DFFFF
#define XPAR_XCSUDMA_1_CSUDMA_CLK_FREQ_HZ 0


/******************************************************************/


/* Definitions for peripheral NOC_0 */
#define XPAR_AXI_NOC_DDR_LOW_0_BASEADDR 0x00000000
#define XPAR_AXI_NOC_DDR_LOW_0_HIGHADDR 0x7FFFFFFF


/******************************************************************/

/* Definitions for driver EMACPS */
#define XPAR_XEMACPS_NUM_INSTANCES 2

/* Definitions for peripheral PSV_ETHERNET_0 */
#define XPAR_PSV_ETHERNET_0_DEVICE_ID 0
#define XPAR_PSV_ETHERNET_0_BASEADDR 0xFF0C0000
#define XPAR_PSV_ETHERNET_0_HIGHADDR 0xFF0CFFFF
#define XPAR_PSV_ETHERNET_0_ENET_CLK_FREQ_HZ 124998749
#define XPAR_PSV_ETHERNET_0_ENET_SLCR_1000MBPS_DIV0 1
#define XPAR_PSV_ETHERNET_0_ENET_SLCR_1000MBPS_DIV1 1
#define XPAR_PSV_ETHERNET_0_ENET_SLCR_100MBPS_DIV0 1
#define XPAR_PSV_ETHERNET_0_ENET_SLCR_100MBPS_DIV1 1
#define XPAR_PSV_ETHERNET_0_ENET_SLCR_10MBPS_DIV0 1
#define XPAR_PSV_ETHERNET_0_ENET_SLCR_10MBPS_DIV1 1
#define XPAR_PSV_ETHERNET_0_ENET_TSU_CLK_FREQ_HZ 249997498


/* Definitions for peripheral PSV_ETHERNET_1 */
#define XPAR_PSV_ETHERNET_1_DEVICE_ID 1
#define XPAR_PSV_ETHERNET_1_BASEADDR 0xFF0D0000
#define XPAR_PSV_ETHERNET_1_HIGHADDR 0xFF0DFFFF
#define XPAR_PSV_ETHERNET_1_ENET_CLK_FREQ_HZ 124998749
#define XPAR_PSV_ETHERNET_1_ENET_SLCR_1000MBPS_DIV0 1
#define XPAR_PSV_ETHERNET_1_ENET_SLCR_1000MBPS_DIV1 1
#define XPAR_PSV_ETHERNET_1_ENET_SLCR_100MBPS_DIV0 1
#define XPAR_PSV_ETHERNET_1_ENET_SLCR_100MBPS_DIV1 1
#define XPAR_PSV_ETHERNET_1_ENET_SLCR_10MBPS_DIV0 1
#define XPAR_PSV_ETHERNET_1_ENET_SLCR_10MBPS_DIV1 1
#define XPAR_PSV_ETHERNET_1_ENET_TSU_CLK_FREQ_HZ 249997498


/******************************************************************/

#define XPAR_PSV_ETHERNET_0_IS_CACHE_COHERENT 0
#define XPAR_XEMACPS_0_IS_CACHE_COHERENT 0
#define XPAR_PSV_ETHERNET_1_IS_CACHE_COHERENT 0
#define XPAR_XEMACPS_1_IS_CACHE_COHERENT 0
/* Canonical definitions for peripheral PSV_ETHERNET_0 */
#define XPAR_XEMACPS_0_DEVICE_ID XPAR_PSV_ETHERNET_0_DEVICE_ID
#define XPAR_XEMACPS_0_BASEADDR 0xFF0C0000
#define XPAR_XEMACPS_0_HIGHADDR 0xFF0CFFFF
#define XPAR_XEMACPS_0_ENET_CLK_FREQ_HZ 124998749
#define XPAR_XEMACPS_0_ENET_SLCR_1000Mbps_DIV0 1
#define XPAR_XEMACPS_0_ENET_SLCR_1000Mbps_DIV1 1
#define XPAR_XEMACPS_0_ENET_SLCR_100Mbps_DIV0 1
#define XPAR_XEMACPS_0_ENET_SLCR_100Mbps_DIV1 1
#define XPAR_XEMACPS_0_ENET_SLCR_10Mbps_DIV0 1
#define XPAR_XEMACPS_0_ENET_SLCR_10Mbps_DIV1 1
#define XPAR_XEMACPS_0_ENET_TSU_CLK_FREQ_HZ 249997498

/* Canonical definitions for peripheral PSV_ETHERNET_1 */
#define XPAR_XEMACPS_1_DEVICE_ID XPAR_PSV_ETHERNET_1_DEVICE_ID
#define XPAR_XEMACPS_1_BASEADDR 0xFF0D0000
#define XPAR_XEMACPS_1_HIGHADDR 0xFF0DFFFF
#define XPAR_XEMACPS_1_ENET_CLK_FREQ_HZ 124998749
#define XPAR_XEMACPS_1_ENET_SLCR_1000Mbps_DIV0 1
#define XPAR_XEMACPS_1_ENET_SLCR_1000Mbps_DIV1 1
#define XPAR_XEMACPS_1_ENET_SLCR_100Mbps_DIV0 1
#define XPAR_XEMACPS_1_ENET_SLCR_100Mbps_DIV1 1
#define XPAR_XEMACPS_1_ENET_SLCR_10Mbps_DIV0 1
#define XPAR_XEMACPS_1_ENET_SLCR_10Mbps_DIV1 1
#define XPAR_XEMACPS_1_ENET_TSU_CLK_FREQ_HZ 249997498


/******************************************************************/


/* Definitions for peripheral PSV_APU_0 */
#define XPAR_PSV_APU_0_S_AXI_BASEADDR 0xFD5C0000
#define XPAR_PSV_APU_0_S_AXI_HIGHADDR 0xFD5CFFFF


/* Definitions for peripheral PSV_CORESIGHT_FPD_ATM */
#define XPAR_PSV_CORESIGHT_FPD_ATM_S_AXI_BASEADDR 0xF0B80000
#define XPAR_PSV_CORESIGHT_FPD_ATM_S_AXI_HIGHADDR 0xF0B8FFFF


/* Definitions for peripheral PSV_CORESIGHT_FPD_STM */
#define XPAR_PSV_CORESIGHT_FPD_STM_S_AXI_BASEADDR 0xF0B70000
#define XPAR_PSV_CORESIGHT_FPD_STM_S_AXI_HIGHADDR 0xF0B7FFFF


/* Definitions for peripheral PSV_CORESIGHT_LPD_ATM */
#define XPAR_PSV_CORESIGHT_LPD_ATM_S_AXI_BASEADDR 0xF0980000
#define XPAR_PSV_CORESIGHT_LPD_ATM_S_AXI_HIGHADDR 0xF098FFFF


/* Definitions for peripheral PSV_FPD_AFI_0 */
#define XPAR_PSV_FPD_AFI_0_S_AXI_BASEADDR 0xFD360000
#define XPAR_PSV_FPD_AFI_0_S_AXI_HIGHADDR 0xFD36FFFF


/* Definitions for peripheral PSV_FPD_AFI_2 */
#define XPAR_PSV_FPD_AFI_2_S_AXI_BASEADDR 0xFD380000
#define XPAR_PSV_FPD_AFI_2_S_AXI_HIGHADDR 0xFD38FFFF


/* Definitions for peripheral PSV_FPD_AFI_MEM_0 */
#define XPAR_PSV_FPD_AFI_MEM_0_S_AXI_BASEADDR 0xA4000000
#define XPAR_PSV_FPD_AFI_MEM_0_S_AXI_HIGHADDR 0xAFFFFFFF


/* Definitions for peripheral PSV_FPD_AFI_MEM_2 */
#define XPAR_PSV_FPD_AFI_MEM_2_S_AXI_BASEADDR 0xB0000000
#define XPAR_PSV_FPD_AFI_MEM_2_S_AXI_HIGHADDR 0xBFFFFFFF


/* Definitions for peripheral PSV_LPD_AFI_0 */
#define XPAR_PSV_LPD_AFI_0_S_AXI_BASEADDR 0xFF9B0000
#define XPAR_PSV_LPD_AFI_0_S_AXI_HIGHADDR 0xFF9BFFFF


/* Definitions for peripheral PSV_LPD_AFI_MEM_0 */
#define XPAR_PSV_LPD_AFI_MEM_0_S_AXI_BASEADDR 0x80000000
#define XPAR_PSV_LPD_AFI_MEM_0_S_AXI_HIGHADDR 0x9FFFFFFF


/* Definitions for peripheral PSV_OCM_CTRL */
#define XPAR_PSV_OCM_CTRL_S_AXI_BASEADDR 0xFF960000
#define XPAR_PSV_OCM_CTRL_S_AXI_HIGHADDR 0xFF96FFFF


/* Definitions for peripheral PSV_OCM_RAM_0 */
#define XPAR_PSV_OCM_RAM_0_S_AXI_BASEADDR 0xFFFC0000
#define XPAR_PSV_OCM_RAM_0_S_AXI_HIGHADDR 0xFFFFFFFF


/* Definitions for peripheral PSV_PMC_AES */
#define XPAR_PSV_PMC_AES_S_AXI_BASEADDR 0xF11E0000
#define XPAR_PSV_PMC_AES_S_AXI_HIGHADDR 0xF11EFFFF


/* Definitions for peripheral PSV_PMC_BBRAM_CTRL */
#define XPAR_PSV_PMC_BBRAM_CTRL_S_AXI_BASEADDR 0xF11F0000
#define XPAR_PSV_PMC_BBRAM_CTRL_S_AXI_HIGHADDR 0xF11FFFFF


/* Definitions for peripheral PSV_PMC_EFUSE_CTRL */
#define XPAR_PSV_PMC_EFUSE_CTRL_S_AXI_BASEADDR 0xF1240000
#define XPAR_PSV_PMC_EFUSE_CTRL_S_AXI_HIGHADDR 0xF124FFFF


/* Definitions for peripheral PSV_PMC_GLOBAL_0 */
#define XPAR_PSV_PMC_GLOBAL_0_S_AXI_BASEADDR 0xF1110000
#define XPAR_PSV_PMC_GLOBAL_0_S_AXI_HIGHADDR 0xF115FFFF


/* Definitions for peripheral PSV_PMC_I2C_0 */
#define XPAR_PSV_PMC_I2C_0_S_AXI_BASEADDR 0xF1000000
#define XPAR_PSV_PMC_I2C_0_S_AXI_HIGHADDR 0xF100FFFF


/* Definitions for peripheral PSV_PMC_RSA */
#define XPAR_PSV_PMC_RSA_S_AXI_BASEADDR 0xF1200000
#define XPAR_PSV_PMC_RSA_S_AXI_HIGHADDR 0xF120FFFF


/* Definitions for peripheral PSV_PMC_SHA */
#define XPAR_PSV_PMC_SHA_S_AXI_BASEADDR 0xF1210000
#define XPAR_PSV_PMC_SHA_S_AXI_HIGHADDR 0xF121FFFF


/* Definitions for peripheral PSV_PSM_GLOBAL_REG */
#define XPAR_PSV_PSM_GLOBAL_REG_S_AXI_BASEADDR 0xFFC90000
#define XPAR_PSV_PSM_GLOBAL_REG_S_AXI_HIGHADDR 0xFFC9EFFF


/* Definitions for peripheral PSV_R5_0_ATCM_GLOBAL */
#define XPAR_PSV_R5_0_ATCM_GLOBAL_S_AXI_BASEADDR 0xFFE00000
#define XPAR_PSV_R5_0_ATCM_GLOBAL_S_AXI_HIGHADDR 0xFFE0FFFF


/* Definitions for peripheral PSV_R5_0_ATCM_LOCKSTEP */
#define XPAR_PSV_R5_0_ATCM_LOCKSTEP_S_AXI_BASEADDR 0xFFE10000
#define XPAR_PSV_R5_0_ATCM_LOCKSTEP_S_AXI_HIGHADDR 0xFFE1FFFF


/* Definitions for peripheral PSV_R5_0_BTCM_GLOBAL */
#define XPAR_PSV_R5_0_BTCM_GLOBAL_S_AXI_BASEADDR 0xFFE20000
#define XPAR_PSV_R5_0_BTCM_GLOBAL_S_AXI_HIGHADDR 0xFFE2FFFF


/* Definitions for peripheral PSV_R5_0_BTCM_LOCKSTEP */
#define XPAR_PSV_R5_0_BTCM_LOCKSTEP_S_AXI_BASEADDR 0xFFE30000
#define XPAR_PSV_R5_0_BTCM_LOCKSTEP_S_AXI_HIGHADDR 0xFFE3FFFF


/* Definitions for peripheral PSV_R5_1_ATCM_GLOBAL */
#define XPAR_PSV_R5_1_ATCM_GLOBAL_S_AXI_BASEADDR 0xFFE90000
#define XPAR_PSV_R5_1_ATCM_GLOBAL_S_AXI_HIGHADDR 0xFFE9FFFF


/* Definitions for peripheral PSV_R5_1_BTCM_GLOBAL */
#define XPAR_PSV_R5_1_BTCM_GLOBAL_S_AXI_BASEADDR 0xFFEB0000
#define XPAR_PSV_R5_1_BTCM_GLOBAL_S_AXI_HIGHADDR 0xFFEBFFFF


/* Definitions for peripheral PSV_R5_TCM_RAM_GLOBAL */
#define XPAR_PSV_R5_TCM_RAM_GLOBAL_S_AXI_BASEADDR 0xFFE00000
#define XPAR_PSV_R5_TCM_RAM_GLOBAL_S_AXI_HIGHADDR 0xFFE3FFFF


/* Definitions for peripheral PSV_RPU_0 */
#define XPAR_PSV_RPU_0_S_AXI_BASEADDR 0xFF9A0000
#define XPAR_PSV_RPU_0_S_AXI_HIGHADDR 0xFF9AFFFF


/* Definitions for peripheral PSV_USB_0 */
#define XPAR_PSV_USB_0_S_AXI_BASEADDR 0xFF9D0000
#define XPAR_PSV_USB_0_S_AXI_HIGHADDR 0xFF9DFFFF


/******************************************************************/

/* Definitions for driver GPIOPS */
#define XPAR_XGPIOPS_NUM_INSTANCES 2

/* Definitions for peripheral PSV_GPIO_2 */
#define XPAR_PSV_GPIO_2_DEVICE_ID 0
#define XPAR_PSV_GPIO_2_BASEADDR 0xFF0B0000
#define XPAR_PSV_GPIO_2_HIGHADDR 0xFF0BFFFF


/* Definitions for peripheral PSV_PMC_GPIO_0 */
#define XPAR_PSV_PMC_GPIO_0_DEVICE_ID 1
#define XPAR_PSV_PMC_GPIO_0_BASEADDR 0xF1020000
#define XPAR_PSV_PMC_GPIO_0_HIGHADDR 0xF102FFFF


/******************************************************************/

/* Canonical definitions for peripheral PSV_GPIO_2 */
#define XPAR_XGPIOPS_0_DEVICE_ID XPAR_PSV_GPIO_2_DEVICE_ID
#define XPAR_XGPIOPS_0_BASEADDR 0xFF0B0000
#define XPAR_XGPIOPS_0_HIGHADDR 0xFF0BFFFF

/* Canonical definitions for peripheral PSV_PMC_GPIO_0 */
#define XPAR_XGPIOPS_1_DEVICE_ID XPAR_PSV_PMC_GPIO_0_DEVICE_ID
#define XPAR_XGPIOPS_1_BASEADDR 0xF1020000
#define XPAR_XGPIOPS_1_HIGHADDR 0xF102FFFF


/******************************************************************/

/* Definitions for driver IICPS */
#define XPAR_XIICPS_NUM_INSTANCES 1

/* Definitions for peripheral PSV_I2C_1 */
#define XPAR_PSV_I2C_1_DEVICE_ID 0
#define XPAR_PSV_I2C_1_BASEADDR 0xFF030000
#define XPAR_PSV_I2C_1_HIGHADDR 0xFF03FFFF
#define XPAR_PSV_I2C_1_I2C_CLK_FREQ_HZ 99999001


/******************************************************************/

/* Canonical definitions for peripheral PSV_I2C_1 */
#define XPAR_XIICPS_0_DEVICE_ID XPAR_PSV_I2C_1_DEVICE_ID
#define XPAR_XIICPS_0_BASEADDR 0xFF030000
#define XPAR_XIICPS_0_HIGHADDR 0xFF03FFFF
#define XPAR_XIICPS_0_I2C_CLK_FREQ_HZ 99999001


/******************************************************************/

#define  XPAR_XIPIPSU_NUM_INSTANCES  7U

/* Parameter definitions for peripheral psv_ipi_0 */
#define  XPAR_PSV_IPI_0_DEVICE_ID  0U
#define  XPAR_PSV_IPI_0_S_AXI_BASEADDR  0xFF330000U
#define  XPAR_PSV_IPI_0_BIT_MASK  0x00000004U
#define  XPAR_PSV_IPI_0_BUFFER_INDEX  0x2U
#define  XPAR_PSV_IPI_0_INT_ID  62U

/* Parameter definitions for peripheral psv_ipi_1 */
#define  XPAR_PSV_IPI_1_DEVICE_ID  1U
#define  XPAR_PSV_IPI_1_S_AXI_BASEADDR  0xFF340000U
#define  XPAR_PSV_IPI_1_BIT_MASK  0x00000008U
#define  XPAR_PSV_IPI_1_BUFFER_INDEX  0x3U
#define  XPAR_PSV_IPI_1_INT_ID  63U

/* Parameter definitions for peripheral psv_ipi_2 */
#define  XPAR_PSV_IPI_2_DEVICE_ID  2U
#define  XPAR_PSV_IPI_2_S_AXI_BASEADDR  0xFF350000U
#define  XPAR_PSV_IPI_2_BIT_MASK  0x00000010U
#define  XPAR_PSV_IPI_2_BUFFER_INDEX  0x4U
#define  XPAR_PSV_IPI_2_INT_ID  64U

/* Parameter definitions for peripheral psv_ipi_3 */
#define  XPAR_PSV_IPI_3_DEVICE_ID  3U
#define  XPAR_PSV_IPI_3_S_AXI_BASEADDR  0xFF360000U
#define  XPAR_PSV_IPI_3_BIT_MASK  0x00000020U
#define  XPAR_PSV_IPI_3_BUFFER_INDEX  0x5U
#define  XPAR_PSV_IPI_3_INT_ID  65U

/* Parameter definitions for peripheral psv_ipi_4 */
#define  XPAR_PSV_IPI_4_DEVICE_ID  4U
#define  XPAR_PSV_IPI_4_S_AXI_BASEADDR  0xFF370000U
#define  XPAR_PSV_IPI_4_BIT_MASK  0x00000040U
#define  XPAR_PSV_IPI_4_BUFFER_INDEX  0x6U
#define  XPAR_PSV_IPI_4_INT_ID  66U

/* Parameter definitions for peripheral psv_ipi_5 */
#define  XPAR_PSV_IPI_5_DEVICE_ID  5U
#define  XPAR_PSV_IPI_5_S_AXI_BASEADDR  0xFF380000U
#define  XPAR_PSV_IPI_5_BIT_MASK  0x00000080U
#define  XPAR_PSV_IPI_5_BUFFER_INDEX  0x7U
#define  XPAR_PSV_IPI_5_INT_ID  67U

/* Parameter definitions for peripheral psv_ipi_6 */
#define  XPAR_PSV_IPI_6_DEVICE_ID  6U
#define  XPAR_PSV_IPI_6_S_AXI_BASEADDR  0xFF3A0000U
#define  XPAR_PSV_IPI_6_BIT_MASK  0x00000200U
#define  XPAR_PSV_IPI_6_BUFFER_INDEX  0xFFFFU
#define  XPAR_PSV_IPI_6_INT_ID  68U

/* Canonical definitions for peripheral psv_ipi_0 */
#define  XPAR_XIPIPSU_0_DEVICE_ID	XPAR_PSV_IPI_0_DEVICE_ID
#define  XPAR_XIPIPSU_0_BASE_ADDRESS	XPAR_PSV_IPI_0_S_AXI_BASEADDR
#define  XPAR_XIPIPSU_0_BIT_MASK	XPAR_PSV_IPI_0_BIT_MASK
#define  XPAR_XIPIPSU_0_BUFFER_INDEX	XPAR_PSV_IPI_0_BUFFER_INDEX
#define  XPAR_XIPIPSU_0_INT_ID	XPAR_PSV_IPI_0_INT_ID

/* Canonical definitions for peripheral psv_ipi_1 */
#define  XPAR_XIPIPSU_1_DEVICE_ID	XPAR_PSV_IPI_1_DEVICE_ID
#define  XPAR_XIPIPSU_1_BASE_ADDRESS	XPAR_PSV_IPI_1_S_AXI_BASEADDR
#define  XPAR_XIPIPSU_1_BIT_MASK	XPAR_PSV_IPI_1_BIT_MASK
#define  XPAR_XIPIPSU_1_BUFFER_INDEX	XPAR_PSV_IPI_1_BUFFER_INDEX
#define  XPAR_XIPIPSU_1_INT_ID	XPAR_PSV_IPI_1_INT_ID

/* Canonical definitions for peripheral psv_ipi_2 */
#define  XPAR_XIPIPSU_2_DEVICE_ID	XPAR_PSV_IPI_2_DEVICE_ID
#define  XPAR_XIPIPSU_2_BASE_ADDRESS	XPAR_PSV_IPI_2_S_AXI_BASEADDR
#define  XPAR_XIPIPSU_2_BIT_MASK	XPAR_PSV_IPI_2_BIT_MASK
#define  XPAR_XIPIPSU_2_BUFFER_INDEX	XPAR_PSV_IPI_2_BUFFER_INDEX
#define  XPAR_XIPIPSU_2_INT_ID	XPAR_PSV_IPI_2_INT_ID

/* Canonical definitions for peripheral psv_ipi_3 */
#define  XPAR_XIPIPSU_3_DEVICE_ID	XPAR_PSV_IPI_3_DEVICE_ID
#define  XPAR_XIPIPSU_3_BASE_ADDRESS	XPAR_PSV_IPI_3_S_AXI_BASEADDR
#define  XPAR_XIPIPSU_3_BIT_MASK	XPAR_PSV_IPI_3_BIT_MASK
#define  XPAR_XIPIPSU_3_BUFFER_INDEX	XPAR_PSV_IPI_3_BUFFER_INDEX
#define  XPAR_XIPIPSU_3_INT_ID	XPAR_PSV_IPI_3_INT_ID

/* Canonical definitions for peripheral psv_ipi_4 */
#define  XPAR_XIPIPSU_4_DEVICE_ID	XPAR_PSV_IPI_4_DEVICE_ID
#define  XPAR_XIPIPSU_4_BASE_ADDRESS	XPAR_PSV_IPI_4_S_AXI_BASEADDR
#define  XPAR_XIPIPSU_4_BIT_MASK	XPAR_PSV_IPI_4_BIT_MASK
#define  XPAR_XIPIPSU_4_BUFFER_INDEX	XPAR_PSV_IPI_4_BUFFER_INDEX
#define  XPAR_XIPIPSU_4_INT_ID	XPAR_PSV_IPI_4_INT_ID

/* Canonical definitions for peripheral psv_ipi_5 */
#define  XPAR_XIPIPSU_5_DEVICE_ID	XPAR_PSV_IPI_5_DEVICE_ID
#define  XPAR_XIPIPSU_5_BASE_ADDRESS	XPAR_PSV_IPI_5_S_AXI_BASEADDR
#define  XPAR_XIPIPSU_5_BIT_MASK	XPAR_PSV_IPI_5_BIT_MASK
#define  XPAR_XIPIPSU_5_BUFFER_INDEX	XPAR_PSV_IPI_5_BUFFER_INDEX
#define  XPAR_XIPIPSU_5_INT_ID	XPAR_PSV_IPI_5_INT_ID

/* Canonical definitions for peripheral psv_ipi_6 */
#define  XPAR_XIPIPSU_6_DEVICE_ID	XPAR_PSV_IPI_6_DEVICE_ID
#define  XPAR_XIPIPSU_6_BASE_ADDRESS	XPAR_PSV_IPI_6_S_AXI_BASEADDR
#define  XPAR_XIPIPSU_6_BIT_MASK	XPAR_PSV_IPI_6_BIT_MASK
#define  XPAR_XIPIPSU_6_BUFFER_INDEX	XPAR_PSV_IPI_6_BUFFER_INDEX
#define  XPAR_XIPIPSU_6_INT_ID	XPAR_PSV_IPI_6_INT_ID

#define  XPAR_XIPIPSU_NUM_TARGETS  10U

#define  XPAR_PSV_IPI_PMC_BIT_MASK  0x00000002U
#define  XPAR_PSV_IPI_PMC_BUFFER_INDEX  0x1U
#define  XPAR_PSV_IPI_PSM_BIT_MASK  0x00000001U
#define  XPAR_PSV_IPI_PSM_BUFFER_INDEX  0x0U
#define  XPAR_PSV_IPI_0_BIT_MASK  0x00000004U
#define  XPAR_PSV_IPI_0_BUFFER_INDEX  0x2U
#define  XPAR_PSV_IPI_1_BIT_MASK  0x00000008U
#define  XPAR_PSV_IPI_1_BUFFER_INDEX  0x3U
#define  XPAR_PSV_IPI_2_BIT_MASK  0x00000010U
#define  XPAR_PSV_IPI_2_BUFFER_INDEX  0x4U
#define  XPAR_PSV_IPI_3_BIT_MASK  0x00000020U
#define  XPAR_PSV_IPI_3_BUFFER_INDEX  0x5U
#define  XPAR_PSV_IPI_4_BIT_MASK  0x00000040U
#define  XPAR_PSV_IPI_4_BUFFER_INDEX  0x6U
#define  XPAR_PSV_IPI_5_BIT_MASK  0x00000080U
#define  XPAR_PSV_IPI_5_BUFFER_INDEX  0x7U
#define  XPAR_PSV_IPI_PMC_NOBUF_BIT_MASK  0x00000100U
#define  XPAR_PSV_IPI_PMC_NOBUF_BUFFER_INDEX  0xFFFFU
#define  XPAR_PSV_IPI_6_BIT_MASK  0x00000200U
#define  XPAR_PSV_IPI_6_BUFFER_INDEX  0xFFFFU
/* Target List for referring to processor IPI Targets */

#define  XPAR_XIPIPS_TARGET_PSV_PMC_0_CH0_MASK  XPAR_PSV_IPI_PMC_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_PMC_0_CH0_INDEX  0U
#define  XPAR_XIPIPS_TARGET_PSV_PMC_0_CH1_MASK  XPAR_PSV_IPI_PMC_NOBUF_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_PMC_0_CH1_INDEX  8U

#define  XPAR_XIPIPS_TARGET_PSV_PSM_0_CH0_MASK  XPAR_PSV_IPI_PSM_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_PSM_0_CH0_INDEX  1U

#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_0_CH0_MASK  XPAR_PSV_IPI_0_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_0_CH0_INDEX  2U
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_0_CH1_MASK  XPAR_PSV_IPI_1_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_0_CH1_INDEX  3U
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_0_CH2_MASK  XPAR_PSV_IPI_2_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_0_CH2_INDEX  4U
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_0_CH3_MASK  XPAR_PSV_IPI_3_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_0_CH3_INDEX  5U
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_0_CH4_MASK  XPAR_PSV_IPI_4_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_0_CH4_INDEX  6U
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_0_CH5_MASK  XPAR_PSV_IPI_5_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_0_CH5_INDEX  7U
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_0_CH6_MASK  XPAR_PSV_IPI_6_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_0_CH6_INDEX  9U

#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_1_CH0_MASK  XPAR_PSV_IPI_0_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_1_CH0_INDEX  2U
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_1_CH1_MASK  XPAR_PSV_IPI_1_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_1_CH1_INDEX  3U
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_1_CH2_MASK  XPAR_PSV_IPI_2_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_1_CH2_INDEX  4U
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_1_CH3_MASK  XPAR_PSV_IPI_3_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_1_CH3_INDEX  5U
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_1_CH4_MASK  XPAR_PSV_IPI_4_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_1_CH4_INDEX  6U
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_1_CH5_MASK  XPAR_PSV_IPI_5_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_1_CH5_INDEX  7U
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_1_CH6_MASK  XPAR_PSV_IPI_6_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_1_CH6_INDEX  9U



/* Definitions for driver QSPIPSU */
#define XPAR_XQSPIPSU_NUM_INSTANCES 2

/* Definitions for peripheral PSV_PMC_QSPI_0 */
#define XPAR_PSV_PMC_QSPI_0_DEVICE_ID 0
#define XPAR_PSV_PMC_QSPI_0_BASEADDR 0xF1030000
#define XPAR_PSV_PMC_QSPI_0_HIGHADDR 0xF103FFFF
#define XPAR_PSV_PMC_QSPI_0_QSPI_CLK_FREQ_HZ 149998505
#define XPAR_PSV_PMC_QSPI_0_QSPI_MODE 2
#define XPAR_PSV_PMC_QSPI_0_QSPI_BUS_WIDTH 2


/* Definitions for peripheral PSV_PMC_QSPI_OSPI_FLASH_0 */
#define XPAR_PSV_PMC_QSPI_OSPI_FLASH_0_DEVICE_ID 1
#define XPAR_PSV_PMC_QSPI_OSPI_FLASH_0_BASEADDR 0xC0000000
#define XPAR_PSV_PMC_QSPI_OSPI_FLASH_0_HIGHADDR 0xDFFFFFFF
#define XPAR_PSV_PMC_QSPI_OSPI_FLASH_0_QSPI_CLK_FREQ_HZ 0
#define XPAR_PSV_PMC_QSPI_OSPI_FLASH_0_QSPI_MODE 0
#define XPAR_PSV_PMC_QSPI_OSPI_FLASH_0_QSPI_BUS_WIDTH 0


/******************************************************************/

#define XPAR_PSV_PMC_QSPI_0_IS_CACHE_COHERENT 0
#define XPAR_PSV_PMC_QSPI_OSPI_FLASH_0_IS_CACHE_COHERENT 0
/* Canonical definitions for peripheral PSV_PMC_QSPI_0 */
#define XPAR_XQSPIPSU_0_DEVICE_ID XPAR_PSV_PMC_QSPI_0_DEVICE_ID
#define XPAR_XQSPIPSU_0_BASEADDR 0xF1030000
#define XPAR_XQSPIPSU_0_HIGHADDR 0xF103FFFF
#define XPAR_XQSPIPSU_0_QSPI_CLK_FREQ_HZ 149998505
#define XPAR_XQSPIPSU_0_QSPI_MODE 2
#define XPAR_XQSPIPSU_0_QSPI_BUS_WIDTH 2
#define XPAR_XQSPIPSU_0_IS_CACHE_COHERENT 0

/* Canonical definitions for peripheral PSV_PMC_QSPI_OSPI_FLASH_0 */
#define XPAR_XQSPIPSU_1_DEVICE_ID XPAR_PSV_PMC_QSPI_OSPI_FLASH_0_DEVICE_ID
#define XPAR_XQSPIPSU_1_BASEADDR 0xC0000000
#define XPAR_XQSPIPSU_1_HIGHADDR 0xDFFFFFFF
#define XPAR_XQSPIPSU_1_QSPI_CLK_FREQ_HZ 0
#define XPAR_XQSPIPSU_1_QSPI_MODE 0
#define XPAR_XQSPIPSU_1_QSPI_BUS_WIDTH 0
#define XPAR_XQSPIPSU_1_IS_CACHE_COHERENT 0


/******************************************************************/

/* Definitions for driver RTCPSU */
#define XPAR_XRTCPSU_NUM_INSTANCES 1

/* Definitions for peripheral PSV_PMC_RTC_0 */
#define XPAR_PSV_PMC_RTC_0_DEVICE_ID 0
#define XPAR_PSV_PMC_RTC_0_BASEADDR 0xF12A0000
#define XPAR_PSV_PMC_RTC_0_HIGHADDR 0xF12AFFFF


/******************************************************************/

/* Canonical definitions for peripheral PSV_PMC_RTC_0 */
#define XPAR_XRTCPSU_0_DEVICE_ID XPAR_PSV_PMC_RTC_0_DEVICE_ID
#define XPAR_XRTCPSU_0_BASEADDR 0xF12A0000
#define XPAR_XRTCPSU_0_HIGHADDR 0xF12AFFFF


/******************************************************************/

/* Definitions for driver SCUGIC */
#define XPAR_XSCUGIC_NUM_INSTANCES 1U

/* Definitions for peripheral PSV_ACPU_GIC */
#define XPAR_PSV_ACPU_GIC_DEVICE_ID 0U
#define XPAR_PSV_ACPU_GIC_BASEADDR 0xF9040000U
#define XPAR_PSV_ACPU_GIC_HIGHADDR 0xF9041000U
#define XPAR_PSV_ACPU_GIC_DIST_BASEADDR 0xF9000000U


/******************************************************************/

/* Canonical definitions for peripheral PSV_ACPU_GIC */
#define XPAR_SCUGIC_0_DEVICE_ID 0U
#define XPAR_SCUGIC_0_CPU_BASEADDR 0xF9040000U
#define XPAR_SCUGIC_0_CPU_HIGHADDR 0xF9041000U
#define XPAR_SCUGIC_0_DIST_BASEADDR 0xF9000000U


/******************************************************************/

/* Definitions for driver SDPS */
#define XPAR_XSDPS_NUM_INSTANCES 1

/* Definitions for peripheral PSV_PMC_SD_1 */
#define XPAR_PSV_PMC_SD_1_DEVICE_ID 0
#define XPAR_PSV_PMC_SD_1_BASEADDR 0xF1050000
#define XPAR_PSV_PMC_SD_1_HIGHADDR 0xF105FFFF
#define XPAR_PSV_PMC_SD_1_SDIO_CLK_FREQ_HZ 199998001
#define XPAR_PSV_PMC_SD_1_HAS_CD 1
#define XPAR_PSV_PMC_SD_1_HAS_WP 1
#define XPAR_PSV_PMC_SD_1_BUS_WIDTH 8
#define XPAR_PSV_PMC_SD_1_MIO_BANK 1
#define XPAR_PSV_PMC_SD_1_HAS_EMIO 0


/******************************************************************/

#define XPAR_PSV_PMC_SD_1_IS_CACHE_COHERENT 0
/* Canonical definitions for peripheral PSV_PMC_SD_1 */
#define XPAR_XSDPS_0_DEVICE_ID XPAR_PSV_PMC_SD_1_DEVICE_ID
#define XPAR_XSDPS_0_BASEADDR 0xF1050000
#define XPAR_XSDPS_0_HIGHADDR 0xF105FFFF
#define XPAR_XSDPS_0_SDIO_CLK_FREQ_HZ 199998001
#define XPAR_XSDPS_0_HAS_CD 1
#define XPAR_XSDPS_0_HAS_WP 1
#define XPAR_XSDPS_0_BUS_WIDTH 8
#define XPAR_XSDPS_0_MIO_BANK 1
#define XPAR_XSDPS_0_HAS_EMIO 0
#define XPAR_XSDPS_0_IS_CACHE_COHERENT 0


/******************************************************************/

#define XPAR_XSYSMONPSV_NUM_INSTANCES 1

/* Definitions for peripheral PSV_PMC_SYSMON_0 */
#define XPAR_PSV_PMC_SYSMON_0_S_AXI_BASEADDR 0xF1270000
#define XPAR_PSV_PMC_SYSMON_0_S_AXI_HIGHADDR 0xF129FFFF


/******************************************************************/

/* Canonical definitions for peripheral PSV_PMC_SYSMON_0 */
#define XPAR_XSYSMONPSV_0_S_AXI_BASEADDR 0xF1270000
#define XPAR_XSYSMONPSV_0_S_AXI_HIGHADDR 0xF129FFFF

#define XPAR_XSYSMONPSV_0_NO_MEAS	255

/******************************************************************/

/* Xilinx Sysmon Device Name */

/******************************************************************/

/* Definitions for driver TTCPS */
#define XPAR_XTTCPS_NUM_INSTANCES 12U

/* Definitions for peripheral PSV_TTC_0 */
#define XPAR_PSV_TTC_0_DEVICE_ID 0U
#define XPAR_PSV_TTC_0_BASEADDR 0XFF0E0000U
#define XPAR_PSV_TTC_0_TTC_CLK_FREQ_HZ 99999001U
#define XPAR_PSV_TTC_0_TTC_CLK_CLKSRC 0U
#define XPAR_PSV_TTC_1_DEVICE_ID 1U
#define XPAR_PSV_TTC_1_BASEADDR 0XFF0E0004U
#define XPAR_PSV_TTC_1_TTC_CLK_FREQ_HZ 99999001U
#define XPAR_PSV_TTC_1_TTC_CLK_CLKSRC 0U
#define XPAR_PSV_TTC_2_DEVICE_ID 2U
#define XPAR_PSV_TTC_2_BASEADDR 0XFF0E0008U
#define XPAR_PSV_TTC_2_TTC_CLK_FREQ_HZ 99999001U
#define XPAR_PSV_TTC_2_TTC_CLK_CLKSRC 0U


/* Definitions for peripheral PSV_TTC_1 */
#define XPAR_PSV_TTC_3_DEVICE_ID 3U
#define XPAR_PSV_TTC_3_BASEADDR 0XFF0F0000U
#define XPAR_PSV_TTC_3_TTC_CLK_FREQ_HZ 99999001U
#define XPAR_PSV_TTC_3_TTC_CLK_CLKSRC 0U
#define XPAR_PSV_TTC_4_DEVICE_ID 4U
#define XPAR_PSV_TTC_4_BASEADDR 0XFF0F0004U
#define XPAR_PSV_TTC_4_TTC_CLK_FREQ_HZ 99999001U
#define XPAR_PSV_TTC_4_TTC_CLK_CLKSRC 0U
#define XPAR_PSV_TTC_5_DEVICE_ID 5U
#define XPAR_PSV_TTC_5_BASEADDR 0XFF0F0008U
#define XPAR_PSV_TTC_5_TTC_CLK_FREQ_HZ 99999001U
#define XPAR_PSV_TTC_5_TTC_CLK_CLKSRC 0U


/* Definitions for peripheral PSV_TTC_2 */
#define XPAR_PSV_TTC_6_DEVICE_ID 6U
#define XPAR_PSV_TTC_6_BASEADDR 0XFF100000U
#define XPAR_PSV_TTC_6_TTC_CLK_FREQ_HZ 99999001U
#define XPAR_PSV_TTC_6_TTC_CLK_CLKSRC 0U
#define XPAR_PSV_TTC_7_DEVICE_ID 7U
#define XPAR_PSV_TTC_7_BASEADDR 0XFF100004U
#define XPAR_PSV_TTC_7_TTC_CLK_FREQ_HZ 99999001U
#define XPAR_PSV_TTC_7_TTC_CLK_CLKSRC 0U
#define XPAR_PSV_TTC_8_DEVICE_ID 8U
#define XPAR_PSV_TTC_8_BASEADDR 0XFF100008U
#define XPAR_PSV_TTC_8_TTC_CLK_FREQ_HZ 99999001U
#define XPAR_PSV_TTC_8_TTC_CLK_CLKSRC 0U


/* Definitions for peripheral PSV_TTC_3 */
#define XPAR_PSV_TTC_9_DEVICE_ID 9U
#define XPAR_PSV_TTC_9_BASEADDR 0XFF110000U
#define XPAR_PSV_TTC_9_TTC_CLK_FREQ_HZ 99999001U
#define XPAR_PSV_TTC_9_TTC_CLK_CLKSRC 0U
#define XPAR_PSV_TTC_10_DEVICE_ID 10U
#define XPAR_PSV_TTC_10_BASEADDR 0XFF110004U
#define XPAR_PSV_TTC_10_TTC_CLK_FREQ_HZ 99999001U
#define XPAR_PSV_TTC_10_TTC_CLK_CLKSRC 0U
#define XPAR_PSV_TTC_11_DEVICE_ID 11U
#define XPAR_PSV_TTC_11_BASEADDR 0XFF110008U
#define XPAR_PSV_TTC_11_TTC_CLK_FREQ_HZ 99999001U
#define XPAR_PSV_TTC_11_TTC_CLK_CLKSRC 0U


/******************************************************************/

/* Canonical definitions for peripheral PSV_TTC_0 */
#define XPAR_XTTCPS_0_DEVICE_ID XPAR_PSV_TTC_0_DEVICE_ID
#define XPAR_XTTCPS_0_BASEADDR 0xFF0E0000U
#define XPAR_XTTCPS_0_TTC_CLK_FREQ_HZ 99999001U
#define XPAR_XTTCPS_0_TTC_CLK_CLKSRC 0U

#define XPAR_XTTCPS_1_DEVICE_ID XPAR_PSV_TTC_1_DEVICE_ID
#define XPAR_XTTCPS_1_BASEADDR 0xFF0E0004U
#define XPAR_XTTCPS_1_TTC_CLK_FREQ_HZ 99999001U
#define XPAR_XTTCPS_1_TTC_CLK_CLKSRC 0U

#define XPAR_XTTCPS_2_DEVICE_ID XPAR_PSV_TTC_2_DEVICE_ID
#define XPAR_XTTCPS_2_BASEADDR 0xFF0E0008U
#define XPAR_XTTCPS_2_TTC_CLK_FREQ_HZ 99999001U
#define XPAR_XTTCPS_2_TTC_CLK_CLKSRC 0U

/* Canonical definitions for peripheral PSV_TTC_1 */
#define XPAR_XTTCPS_3_DEVICE_ID XPAR_PSV_TTC_3_DEVICE_ID
#define XPAR_XTTCPS_3_BASEADDR 0xFF0F0000U
#define XPAR_XTTCPS_3_TTC_CLK_FREQ_HZ 99999001U
#define XPAR_XTTCPS_3_TTC_CLK_CLKSRC 0U

#define XPAR_XTTCPS_4_DEVICE_ID XPAR_PSV_TTC_4_DEVICE_ID
#define XPAR_XTTCPS_4_BASEADDR 0xFF0F0004U
#define XPAR_XTTCPS_4_TTC_CLK_FREQ_HZ 99999001U
#define XPAR_XTTCPS_4_TTC_CLK_CLKSRC 0U

#define XPAR_XTTCPS_5_DEVICE_ID XPAR_PSV_TTC_5_DEVICE_ID
#define XPAR_XTTCPS_5_BASEADDR 0xFF0F0008U
#define XPAR_XTTCPS_5_TTC_CLK_FREQ_HZ 99999001U
#define XPAR_XTTCPS_5_TTC_CLK_CLKSRC 0U

/* Canonical definitions for peripheral PSV_TTC_2 */
#define XPAR_XTTCPS_6_DEVICE_ID XPAR_PSV_TTC_6_DEVICE_ID
#define XPAR_XTTCPS_6_BASEADDR 0xFF100000U
#define XPAR_XTTCPS_6_TTC_CLK_FREQ_HZ 99999001U
#define XPAR_XTTCPS_6_TTC_CLK_CLKSRC 0U

#define XPAR_XTTCPS_7_DEVICE_ID XPAR_PSV_TTC_7_DEVICE_ID
#define XPAR_XTTCPS_7_BASEADDR 0xFF100004U
#define XPAR_XTTCPS_7_TTC_CLK_FREQ_HZ 99999001U
#define XPAR_XTTCPS_7_TTC_CLK_CLKSRC 0U

#define XPAR_XTTCPS_8_DEVICE_ID XPAR_PSV_TTC_8_DEVICE_ID
#define XPAR_XTTCPS_8_BASEADDR 0xFF100008U
#define XPAR_XTTCPS_8_TTC_CLK_FREQ_HZ 99999001U
#define XPAR_XTTCPS_8_TTC_CLK_CLKSRC 0U

/* Canonical definitions for peripheral PSV_TTC_3 */
#define XPAR_XTTCPS_9_DEVICE_ID XPAR_PSV_TTC_9_DEVICE_ID
#define XPAR_XTTCPS_9_BASEADDR 0xFF110000U
#define XPAR_XTTCPS_9_TTC_CLK_FREQ_HZ 99999001U
#define XPAR_XTTCPS_9_TTC_CLK_CLKSRC 0U

#define XPAR_XTTCPS_10_DEVICE_ID XPAR_PSV_TTC_10_DEVICE_ID
#define XPAR_XTTCPS_10_BASEADDR 0xFF110004U
#define XPAR_XTTCPS_10_TTC_CLK_FREQ_HZ 99999001U
#define XPAR_XTTCPS_10_TTC_CLK_CLKSRC 0U

#define XPAR_XTTCPS_11_DEVICE_ID XPAR_PSV_TTC_11_DEVICE_ID
#define XPAR_XTTCPS_11_BASEADDR 0xFF110008U
#define XPAR_XTTCPS_11_TTC_CLK_FREQ_HZ 99999001U
#define XPAR_XTTCPS_11_TTC_CLK_CLKSRC 0U


/******************************************************************/

/* Definitions for driver UARTLITE */
#define XPAR_XUARTLITE_NUM_INSTANCES 1

/* Definitions for peripheral PSV_PMC_PPU1_MDM_0 */
#define XPAR_PSV_PMC_PPU1_MDM_0_BASEADDR 0xF0310000
#define XPAR_PSV_PMC_PPU1_MDM_0_HIGHADDR 0xF0317FFF
#define XPAR_PSV_PMC_PPU1_MDM_0_DEVICE_ID 0
#define XPAR_PSV_PMC_PPU1_MDM_0_BAUDRATE 0
#define XPAR_PSV_PMC_PPU1_MDM_0_USE_PARITY 0
#define XPAR_PSV_PMC_PPU1_MDM_0_ODD_PARITY 0
#define XPAR_PSV_PMC_PPU1_MDM_0_DATA_BITS 0


/******************************************************************/

/* Canonical definitions for peripheral PSV_PMC_PPU1_MDM_0 */
#define XPAR_UARTLITE_0_DEVICE_ID XPAR_PSV_PMC_PPU1_MDM_0_DEVICE_ID
#define XPAR_UARTLITE_0_BASEADDR 0xF0310000
#define XPAR_UARTLITE_0_HIGHADDR 0xF0317FFF
#define XPAR_UARTLITE_0_BAUDRATE 0
#define XPAR_UARTLITE_0_USE_PARITY 0
#define XPAR_UARTLITE_0_ODD_PARITY 0
#define XPAR_UARTLITE_0_DATA_BITS 0


/******************************************************************/

/* Definitions for driver UARTPSV */
#define XPAR_XUARTPSV_NUM_INSTANCES 1

/* Definitions for peripheral PSV_SBSAUART_0 */
#define XPAR_PSV_SBSAUART_0_DEVICE_ID 0
#define XPAR_PSV_SBSAUART_0_BASEADDR 0xFF000000
#define XPAR_PSV_SBSAUART_0_HIGHADDR 0xFF00FFFF
#define XPAR_PSV_SBSAUART_0_UART_CLK_FREQ_HZ 99999001
#define XPAR_PSV_SBSAUART_0_HAS_MODEM 0


/******************************************************************/

/* Canonical definitions for peripheral PSV_SBSAUART_0 */
#define XPAR_XUARTPSV_0_DEVICE_ID XPAR_PSV_SBSAUART_0_DEVICE_ID
#define XPAR_XUARTPSV_0_BASEADDR 0xFF000000
#define XPAR_XUARTPSV_0_HIGHADDR 0xFF00FFFF
#define XPAR_XUARTPSV_0_UART_CLK_FREQ_HZ 99999001
#define XPAR_XUARTPSV_0_HAS_MODEM 0


/******************************************************************/

/* Definitions for driver USBPSU */
#define XPAR_XUSBPSU_NUM_INSTANCES 1

/* Definitions for peripheral PSV_USB_XHCI_0 */
#define XPAR_PSV_USB_XHCI_0_DEVICE_ID 0
#define XPAR_PSV_USB_XHCI_0_BASEADDR 0xFE200000
#define XPAR_PSV_USB_XHCI_0_HIGHADDR 0xFE2FFFFF


/******************************************************************/

#define XPAR_PSV_USB_XHCI_0_IS_CACHE_COHERENT 0
#define XPAR_PSV_USB_XHCI_0_SUPER_SPEED 0
/* Canonical definitions for peripheral PSV_USB_XHCI_0 */
#define XPAR_XUSBPSU_0_DEVICE_ID XPAR_PSV_USB_XHCI_0_DEVICE_ID
#define XPAR_XUSBPSU_0_BASEADDR 0xFE200000
#define XPAR_XUSBPSU_0_HIGHADDR 0xFE2FFFFF


/******************************************************************/

/* Definitions for driver WDTTB */
#define XPAR_XWDTTB_NUM_INSTANCES 1

/* Definitions for peripheral PSV_WWDT_0 */
#define XPAR_PSV_WWDT_0_DEVICE_ID 0
#define XPAR_PSV_WWDT_0_BASEADDR 0xFF120000
#define XPAR_PSV_WWDT_0_HIGHADDR 0xFF12FFFF
#define XPAR_PSV_WWDT_0_WDT_CLK_FREQ_HZ 100.000000


/******************************************************************/

/* Canonical definitions for peripheral PSV_WWDT_0 */
#define XPAR_WDTTB_0_DEVICE_ID XPAR_PSV_WWDT_0_DEVICE_ID
#define XPAR_WDTTB_0_BASEADDR 0xFF120000
#define XPAR_WDTTB_0_HIGHADDR 0xFF12FFFF
#define XPAR_WDTTB_0_WDT_CLK_FREQ_HZ 100.000000


/******************************************************************/

/* Definitions for driver ZDMA */
#define XPAR_XZDMA_NUM_INSTANCES 8

/* Definitions for peripheral PSV_ADMA_0 */
#define XPAR_PSV_ADMA_0_DEVICE_ID 0
#define XPAR_PSV_ADMA_0_BASEADDR 0xFFA80000
#define XPAR_PSV_ADMA_0_DMA_MODE 1
#define XPAR_PSV_ADMA_0_HIGHADDR 0xFFA8FFFF
#define XPAR_PSV_ADMA_0_ZDMA_CLK_FREQ_HZ 0


/* Definitions for peripheral PSV_ADMA_1 */
#define XPAR_PSV_ADMA_1_DEVICE_ID 1
#define XPAR_PSV_ADMA_1_BASEADDR 0xFFA90000
#define XPAR_PSV_ADMA_1_DMA_MODE 1
#define XPAR_PSV_ADMA_1_HIGHADDR 0xFFA9FFFF
#define XPAR_PSV_ADMA_1_ZDMA_CLK_FREQ_HZ 0


/* Definitions for peripheral PSV_ADMA_2 */
#define XPAR_PSV_ADMA_2_DEVICE_ID 2
#define XPAR_PSV_ADMA_2_BASEADDR 0xFFAA0000
#define XPAR_PSV_ADMA_2_DMA_MODE 1
#define XPAR_PSV_ADMA_2_HIGHADDR 0xFFAAFFFF
#define XPAR_PSV_ADMA_2_ZDMA_CLK_FREQ_HZ 0


/* Definitions for peripheral PSV_ADMA_3 */
#define XPAR_PSV_ADMA_3_DEVICE_ID 3
#define XPAR_PSV_ADMA_3_BASEADDR 0xFFAB0000
#define XPAR_PSV_ADMA_3_DMA_MODE 1
#define XPAR_PSV_ADMA_3_HIGHADDR 0xFFABFFFF
#define XPAR_PSV_ADMA_3_ZDMA_CLK_FREQ_HZ 0


/* Definitions for peripheral PSV_ADMA_4 */
#define XPAR_PSV_ADMA_4_DEVICE_ID 4
#define XPAR_PSV_ADMA_4_BASEADDR 0xFFAC0000
#define XPAR_PSV_ADMA_4_DMA_MODE 1
#define XPAR_PSV_ADMA_4_HIGHADDR 0xFFACFFFF
#define XPAR_PSV_ADMA_4_ZDMA_CLK_FREQ_HZ 0


/* Definitions for peripheral PSV_ADMA_5 */
#define XPAR_PSV_ADMA_5_DEVICE_ID 5
#define XPAR_PSV_ADMA_5_BASEADDR 0xFFAD0000
#define XPAR_PSV_ADMA_5_DMA_MODE 1
#define XPAR_PSV_ADMA_5_HIGHADDR 0xFFADFFFF
#define XPAR_PSV_ADMA_5_ZDMA_CLK_FREQ_HZ 0


/* Definitions for peripheral PSV_ADMA_6 */
#define XPAR_PSV_ADMA_6_DEVICE_ID 6
#define XPAR_PSV_ADMA_6_BASEADDR 0xFFAE0000
#define XPAR_PSV_ADMA_6_DMA_MODE 1
#define XPAR_PSV_ADMA_6_HIGHADDR 0xFFAEFFFF
#define XPAR_PSV_ADMA_6_ZDMA_CLK_FREQ_HZ 0


/* Definitions for peripheral PSV_ADMA_7 */
#define XPAR_PSV_ADMA_7_DEVICE_ID 7
#define XPAR_PSV_ADMA_7_BASEADDR 0xFFAF0000
#define XPAR_PSV_ADMA_7_DMA_MODE 1
#define XPAR_PSV_ADMA_7_HIGHADDR 0xFFAFFFFF
#define XPAR_PSV_ADMA_7_ZDMA_CLK_FREQ_HZ 0


/******************************************************************/

#define XPAR_PSV_ADMA_0_IS_CACHE_COHERENT 0
#define XPAR_PSV_ADMA_1_IS_CACHE_COHERENT 0
#define XPAR_PSV_ADMA_2_IS_CACHE_COHERENT 0
#define XPAR_PSV_ADMA_3_IS_CACHE_COHERENT 0
#define XPAR_PSV_ADMA_4_IS_CACHE_COHERENT 0
#define XPAR_PSV_ADMA_5_IS_CACHE_COHERENT 0
#define XPAR_PSV_ADMA_6_IS_CACHE_COHERENT 0
#define XPAR_PSV_ADMA_7_IS_CACHE_COHERENT 0
/* Canonical definitions for peripheral PSV_ADMA_0 */
#define XPAR_XZDMA_0_DEVICE_ID XPAR_PSV_ADMA_0_DEVICE_ID
#define XPAR_XZDMA_0_BASEADDR 0xFFA80000
#define XPAR_XZDMA_0_DMA_MODE 1
#define XPAR_XZDMA_0_HIGHADDR 0xFFA8FFFF
#define XPAR_XZDMA_0_ZDMA_CLK_FREQ_HZ 0

/* Canonical definitions for peripheral PSV_ADMA_1 */
#define XPAR_XZDMA_1_DEVICE_ID XPAR_PSV_ADMA_1_DEVICE_ID
#define XPAR_XZDMA_1_BASEADDR 0xFFA90000
#define XPAR_XZDMA_1_DMA_MODE 1
#define XPAR_XZDMA_1_HIGHADDR 0xFFA9FFFF
#define XPAR_XZDMA_1_ZDMA_CLK_FREQ_HZ 0

/* Canonical definitions for peripheral PSV_ADMA_2 */
#define XPAR_XZDMA_2_DEVICE_ID XPAR_PSV_ADMA_2_DEVICE_ID
#define XPAR_XZDMA_2_BASEADDR 0xFFAA0000
#define XPAR_XZDMA_2_DMA_MODE 1
#define XPAR_XZDMA_2_HIGHADDR 0xFFAAFFFF
#define XPAR_XZDMA_2_ZDMA_CLK_FREQ_HZ 0

/* Canonical definitions for peripheral PSV_ADMA_3 */
#define XPAR_XZDMA_3_DEVICE_ID XPAR_PSV_ADMA_3_DEVICE_ID
#define XPAR_XZDMA_3_BASEADDR 0xFFAB0000
#define XPAR_XZDMA_3_DMA_MODE 1
#define XPAR_XZDMA_3_HIGHADDR 0xFFABFFFF
#define XPAR_XZDMA_3_ZDMA_CLK_FREQ_HZ 0

/* Canonical definitions for peripheral PSV_ADMA_4 */
#define XPAR_XZDMA_4_DEVICE_ID XPAR_PSV_ADMA_4_DEVICE_ID
#define XPAR_XZDMA_4_BASEADDR 0xFFAC0000
#define XPAR_XZDMA_4_DMA_MODE 1
#define XPAR_XZDMA_4_HIGHADDR 0xFFACFFFF
#define XPAR_XZDMA_4_ZDMA_CLK_FREQ_HZ 0

/* Canonical definitions for peripheral PSV_ADMA_5 */
#define XPAR_XZDMA_5_DEVICE_ID XPAR_PSV_ADMA_5_DEVICE_ID
#define XPAR_XZDMA_5_BASEADDR 0xFFAD0000
#define XPAR_XZDMA_5_DMA_MODE 1
#define XPAR_XZDMA_5_HIGHADDR 0xFFADFFFF
#define XPAR_XZDMA_5_ZDMA_CLK_FREQ_HZ 0

/* Canonical definitions for peripheral PSV_ADMA_6 */
#define XPAR_XZDMA_6_DEVICE_ID XPAR_PSV_ADMA_6_DEVICE_ID
#define XPAR_XZDMA_6_BASEADDR 0xFFAE0000
#define XPAR_XZDMA_6_DMA_MODE 1
#define XPAR_XZDMA_6_HIGHADDR 0xFFAEFFFF
#define XPAR_XZDMA_6_ZDMA_CLK_FREQ_HZ 0

/* Canonical definitions for peripheral PSV_ADMA_7 */
#define XPAR_XZDMA_7_DEVICE_ID XPAR_PSV_ADMA_7_DEVICE_ID
#define XPAR_XZDMA_7_BASEADDR 0xFFAF0000
#define XPAR_XZDMA_7_DMA_MODE 1
#define XPAR_XZDMA_7_HIGHADDR 0xFFAFFFFF
#define XPAR_XZDMA_7_ZDMA_CLK_FREQ_HZ 0


/******************************************************************/

#endif  /* end of protection macro */
